FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY config  ./config
COPY core ./core
COPY src ./src
COPY utils ./utils

EXPOSE 8080

CMD ["uvicorn","backend.main:app", "--host", "0.0.0.0", "--port", "8080" ]

