apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-travel-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: app.seu-dominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-travel-frontend-service
                port:
                  number: 80
    - host: api.seu-dominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-travel-backend-service
                port:
                  number: 80